### ISSUE TITLE
How to use it with JB Rider

### ISSUE THREAD

**Issue by DmitryKomarov** [reportportal/agent-net-xunit#23]
I have a test project and I need make reports from rider. But for me it works only in Visual Studio.
Is it possible to use rider?
If not, is it going to be added?

**Comment by nvborisenko** [comment]
I think Rider uses his own runner to discover/execute xUnit tests. And, I guess, `xunit.runner.visualstudio` package is not relevant. So the question can be addressed to JB team to add support of custom reporters like ReportPortal. We cannot be "injected" into his runner.

Closing it for now, please return back here when JB becomes more friendly with xunit custom reporters.
