### ISSUE TITLE
Auto-tests aren't reported to RP with xunit.runner.visualstudio 2.5.0

### ISSUE THREAD

**Issue by Diptan** [reportportal/agent-net-xunit#26]
After xunit.runner.visualstudio update from 2.4.5 to 2.5.0  tests stopped being shown in Report portal.
![image_2023_07_24T13_56_54_584Z](https://github.com/reportportal/agent-net-xunit/assets/11075120/f9fe570a-bc83-4175-b420-c8c7b29469eb)

**Comment by nvborisenko** [comment]
Fixed in 2.4.6
