### ISSUE TITLE
Auto-tests aren't reported to RP with xunit.runner.visualstudio 2.5.1

### ISSUE THREAD

**Issue by Diptan** [reportportal/agent-net-xunit#27]
After xunit.runner.visualstudio update from 2.5.0 to 2.5.1 tests stopped being shown in Report portal.

Version of ReportPortal.XUnit: 2.5.0
Target framework: .NET 6.0

**Comment by Aleh-Yanushkevich** [comment]
Hey @Diptan,

Thank you for posting the issue. Changes in `xunit.runner.visualstudio` led to this behavior. We have created appropriate issue xunit/visualstudio.xunit#385 on the xunit board. We are waiting while it will be resolved.

**Comment by Aleh-Yanushkevich** [comment]
@Diptan could you please try to use `xunit.runner.visualstudio` with version `2.5.2-pre.8`? It works fine for me and if it will work for you, we can close the bug.

**Comment by nvborisenko** [comment]
2.5.3 is released, @Diptan  @Aleh-Yanushkevich can you verify? And, hopefully, there are no changes required on our side.

**Comment by Aleh-Yanushkevich** [comment]
@nvborisenko I did it. It works fine. @Diptan could you please check on your side?

**Comment by Diptan** [comment]
Hi @Aleh-Yanushkevich @nvborisenko. Sorry for the delay. Yes, it works fine with 2.5.3. Thank you

**Comment by nvborisenko** [comment]
Thank you guys!
