### ISSUE TITLE
Overriding "enabled" section for xuint console-runner.

### ISSUE THREAD

**Issue by rdcm** [reportportal/agent-net-xunit#8]
Hi!

Our team starts using the report portal with your xunit adapter. We have different projects with several tests runners, xunit (win/core), nunit(win/core). The main goal collect reports only from branch master, and for this behaviour we set env variable `REPORTPORTAL_ENABLE=true` only in master.  All work as expected, but for one assembly we need to run tests with  xunit.console.exe on windows. For this setup config stored out of the code repository and `enabled` section does not overriding.

Could you suggest a solution for this case?
Would be perfect if I could pass a special argument for disabling metrics collection.

**Comment by nvborisenko** [comment]
Works for me.
I have opened `cmd` and executed:
```cmd
xunit.console.exe <tests.dll>
```
Results are published to RP.
Then:
```cmd
set reportportal_enabled=false
xunit.console.exe <tests.dll>
```
Results are NOT published to RP.

Try to verify env variable name, it should be `reportportal_enabled`. Verify versions of ReportPortal.*.dll files, recommended to be the latest. Verify you set env variable properly, which is applied for xunit runner process.

**Comment by rdcm** [comment]
Hi!
Sorry for the long waiting, look like a bug in the CI file. If this issue will be reproduced in the future, I reopen it.
