### ISSUE TITLE
No logs output in GitLab CI Job

### ISSUE THREAD

**Issue by rdcm** [reportportal/agent-net-xunit#9]
Hi!

We use the report portal for several months and detected an issue when our test fails logs available only in report portal UI, is it possible to write logs to both places GitLab ci job and report portal UI?

**Comment by nvborisenko** [comment]
Hi @rdcm
did you see output messages before starting usage of RP?

**Comment by DzmitryHumianiuk** [comment]
@rdcm ?

**Comment by rdcm** [comment]
@nvborisenko @DzmitryHumianiuk
Definitely yes.

We run selenium tests on windows build-agents, and use RP integration solution for xunit console runner.
RP nice tool for getting statistics about flaky tests for long periods (several months), but for quick reaction to error, more simple way just read the log from GitLab ci job.

`xunit.console.exe`: 2.4.1
`ReportPortal.config.json`:
```
{
  "$schema": "https://raw.githubusercontent.com/reportportal/agent-net-xunit/master/src/ReportPortal.XUnitReporter/ReportPortal.config.schema",
  "enabled": true,
  "server": {
    "URL": "...", // report portal url
    "project": "...", // project name
    "authentication": {
      "uuid": "..." // uuid token 
    }
  },
  "launch": {
    "name": "...", // launch name
    "description": "acceptance tests",
    "debugMode": false,
    "attributes": ["win-builder1","os:win10"],
  }
}
```
`ReportPortal.XUnit`: 1.3.1
`ReportPortal`: 5.2.2

**Comment by rdcm** [comment]
Same behaviour for `ReportPortal.XUnit: 2.0.0`

**Comment by ml21** [comment]
Same behaviour for `https://github.com/reportportal/agent-net-xunit#xunitconsoleexe` with `xunit console runner - 2.4.1`

**Comment by ml21** [comment]
@nvborisenko , everything works, thank you!
